# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@5.0.3

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  run_api_tests:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm install
          name: install dependencies
      - run:
          command: npm run-script api
          name: run api tests
  run_e2e_tests:
    docker:
      - image: mcr.microsoft.com/playwright:v1.23.1-focal
    steps:
      - checkout
      - run: npm i -D @playwright/test
      - run: npx playwright install
      - run: npx playwright install chrome
      - run:
          name: Run test
          command: npm run-script e2e
      - store_artifacts:
          path: /e2e-report
      - store_test_results:
          path: /e2e-report

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  tests-workflow:
    jobs:
      - run_api_tests
      - run_e2e_tests
